### ISSUE TITLE
Support for Prompt Caching/Restoring from llama-rs?

### ISSUE THREAD

**Issue by end-me-please** [Atome-FE/llama-node#24]
would be great for performance

**Comment by hlhr202** [comment]
@end-me-please nice suggestion. but i will wait until llama-rs merge the stadalone load feature cuz i think there will be a lot change made to the model loading and session snapshot is heavily depends on it. 

also i m thinking the way i should expose it since i have to provide a consistant api on the higher level to adapt to different inference backends like llama.cpp. probably i will only expose this just on the llama-rs api level but not llama-node wrapper.

**Comment by end-me-please** [comment]
looks like it has been merged now?

**Comment by hlhr202** [comment]
yes, will consider this soon.

**Comment by hlhr202** [comment]
> btw, does the new loader mean that the llama-rs backend will work with mmap-ed models now?

@end-me-please for now, yes. llama-rs backend has supported GGJT format.

**Comment by hlhr202** [comment]
@end-me-please cached session was supported since 0.0.33. slightly different from llama-rs original implementation, in llama-node, you will only need one parameter "persistSession" as path string to be treated as both readable and writable session cached file.

ts interface
https://github.com/Atome-FE/llama-node/blob/main/packages/core/index.d.ts#L159

rust implentation
https://github.com/Atome-FE/llama-node/blob/main/packages/core/src/llama.rs#L207
https://github.com/Atome-FE/llama-node/blob/main/packages/core/src/llama.rs#L197

**Comment by end-me-please** [comment]
🤔 only one, for both reading and writing?
does that mean that it is not possible to load the same session file multiple times, to reduce load times? (possible use case mentioned in llama-rs)

**Comment by hlhr202** [comment]
> 🤔 only one, for both reading and writing? does that mean that it is not possible to load the same session file multiple times, to reduce load times? (possible use case mentioned in llama-rs)

Hi. infact if your purpose is to reduce model load time, you dont even need to load session from cache file. just keep the llama instance in your memory thats enough. we will keep the model in your memory and you can do inference for multiple times.

eg.
llama.load(loadParams)
llama.inference(firstPrompt)
llama.inference(secondPrompt)

for this example, llama will only load model file once but it can be used for inferencing multiple times. everytime it will automatically create a new session without loading model again.

**Comment by end-me-please** [comment]
what i meant was sending the first half of a prompt (like the "### Instruction:" part), saving the session, and later loading that session with the second half of the prompt 
 
 so that it doesnt have to process the part of the input that doesnt change every time again

**Comment by hlhr202** [comment]
> what i meant was sending the first half of a prompt (like the "### Instruction:" part), saving the session, and later loading that session with the second half of the prompt
> 
> so that it doesnt have to process the part of the input that doesnt change every time again

okay i v got what you mean here. i think except for load and save with separate path arguments, you still need something similar to feedprompt in llama-rs.
i will try to achieve this in the next iteration. but this also means llama-rs backend will have extra method compared to llama.cpp/rwkv.cpp backends. and you can only use this alone with llama-rs backend.

**Comment by hlhr202** [comment]
@end-me-please could you help me see if
https://github.com/Atome-FE/llama-node/pull/35
meets your need?

basically, you can save a session to a file without doing any inference, then load it later and do inference.

**Comment by hlhr202** [comment]
@end-me-please Hi, you can try 0.0.34 for this feature

**Comment by end-me-please** [comment]
@hlhr202 it works, great!
though, how do i know when it finished?
await-ing doesnt seem to work, and since it doesnt call the callback that won't work either

**Comment by hlhr202** [comment]
> @hlhr202 it works, great! though, how do i know when it finished? await-ing doesnt seem to work, and since it doesnt call the callback that won't work either

Emm introduced a new bug here, will fix this soon.
